apiVersion: apps/v1
kind: Deployment
metadata:
  name: restate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restate
  template:
    metadata:
      labels:
        app: restate
    spec:
      containers:
        - name: restate
          image: docker.io/restatedev/restate:latest
          ports:
            - name: ingress
              containerPort: 8080
            - name: admin
              containerPort: 9070
---
apiVersion: v1
kind: Service
metadata:
  name: restate
spec:
  selector:
    app: restate
  ports:
    - name: ingress
      port: 8080
      targetPort: 8080
    - name: admin
      port: 9070
      targetPort: 9070
