apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: agent-platform
spec:
  project: default
  source:
    repoURL: 'https://github.com/MathFrenchToast/durable-agents-k8s.git'
    targetRevision: HEAD
    path: v1-extensible/gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
