apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: agent-platform
spec:
  project: default
  source:
    repoURL: 'https://github.com/mon-orga/agent-platform-gitops.git'
    targetRevision: HEAD
    path: gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: agent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
